### PR TITLE
try fixes   github-oauth.github.com is not defined.

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@jails any idea for it ?

**Comment by jails** [comment]
It brokes a couple of month ago with no specific reason. Only PR made from the Kahlan repo seems to work fine.
I regenerated the auth key on the dev branch so I hope it'll work better.

**Comment by jails** [comment]
fixed in https://github.com/kahlan/kahlan/commit/4169cf86c649a3b034f624677b17be60c3720ae1

**Comment by samsonasik** [comment]
👍

**Pull request closed without merging**
