### PR TITLE
Throw Exception on non-callable actual in ToMatchEcho

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by jails** [comment]
Imo we shouldn't support this as it's a duplicate of `toMatch()`. Why not throwing a more meaningful error message instead ?

**Comment by samsonasik** [comment]
@jails done, I've updated with `throw new InvalidArgumentException('actual must be callable')`

**Comment by jails** [comment]
Perfect thanks :+1: !

**Pull request merged**
