### PR TITLE
Fixed broken example in the README.md

### PR DESCRIPTION
**Pull request by ddziaduch**
Hi!

The example in the README.md seems to be broken. I think I have fixed it :)

### CODE REVIEW

**Comment by jails** [comment]
Good catch :+1: , can you open it on the `dev` branch instead plz ?

**Comment by samsonasik** [comment]
I've changed the target branch to dev, seems mergeable now.

**Comment by ddziaduch** [comment]
Ah sorry I missed that :(

**Comment by samsonasik** [comment]
@ddziaduch nvm, I've changed the target branch to dev. merged. Thanks ;)

**Pull request merged**
