### PR TITLE
try re-fix #343

### LINKED ISSUE #343: Problem with composer autoload files
Having this in the projects composer.json

```
"require": {
    "php": "^7.4",
    "phunkie/phunkie": "^0.11.1"
  },
  "require-dev": {
    "kahlan/kahlan": "^4.7.2"
  }
```

and running `vendor/bin/kahlan`

results in this output

```
Notice: Constant Option already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 14
PHP Notice:  Constant ImmList already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 15

Notice: Constant ImmList already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 15
PHP Notice:  Constant ImmSet already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 16

Notice: Constant ImmSet already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 16
PHP Notice:  Constant Function1 already defined in /tmp/kahlan/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 17

Notice: Constant Function1 already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 17
PHP Notice:  Constant _ already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 18

Notice: Constant _ already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 18
PHP Notice:  Constant None already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 19

Notice: Constant None already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 19
PHP Notice:  Constant Nil already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 20

Notice: Constant Nil already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 20
```

### PR DESCRIPTION
**Pull request by samsonasik**
try re-fix #343 by move in_array($file, $this->_files) after set include path

### CODE REVIEW

**Comment by samsonasik** [comment]
hm..., not really works, will check again.

**Comment by samsonasik** [comment]
I got solution for it, using `@` on require fix it. Tried in my package as well.

**Comment by samsonasik** [comment]
tried at https://github.com/samsonasik/kahlan-issue-343/blob/803c7523facebab05c3da5fc4299aaba3499a4c1/composer.json#L7 and it fixed the issue ,see https://github.com/samsonasik/kahlan-issue-343/actions/runs/75599951

**Comment by jails** [comment]
Since @ won't be supported by PHP8 I'm changing this in 4.7.7.
The issue in https://github.com/kahlan/kahlan/issues/343 was related to manually included files using the `require_once` statement in the phunkie library. Since Kahlan caches patched files in `/tmp`, `require_once` was unable to catch that some files where previously required.
So for now I'll simply ignore notice errors until the composer autoload-files are fully required.
After that step Composer should handle all the requirements with simple `require` statements so all errors can be reported back.

**Pull request merged**
