### PR TITLE
Adjust pretty name of closures on PHP 8.4

### PR DESCRIPTION
**Pull request by staabm**
related to https://github.com/php/php-src/pull/13550

see analog symfony change: https://github.com/symfony/symfony/pull/54614

### CODE REVIEW

**Comment by samsonasik** [comment]
Could you try pin phpcs to 3.7.2 temporary?

**Comment by samsonasik** [comment]
I changed target branch to dev, could you resolve the conflict? Thank you.

**Comment by staabm** [comment]
done

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @staabm

**Pull request merged**
