### PR TITLE
Added ToBeOneOf Matcher

### PR DESCRIPTION
**Pull request by samsonasik**
in favor of #170 #106

### CODE REVIEW

**Comment by LostKobrakai** [comment]
How about using `ToContain::match($expected, $actual)`, as it's essentially the same computation, but $actual and $expected are switched up.

**Comment by samsonasik** [comment]
yes, that same. it is for syntax sugar as described at https://github.com/kahlan/kahlan/issues/106#issuecomment-162968945 . I can update the code to be reverse of `ToContain` if needed.

**Comment by samsonasik** [comment]
@LostKobrakai oh, is what you mean by use `ToContain::match()` inside the `ToBeOneOf::match()`?

**Comment by samsonasik** [comment]
closing in favor of https://github.com/kahlan/extra-matcher

**Pull request closed without merging**
