### PR TITLE
[4.0] update php requirement to 5.5+ in readme

### PR DESCRIPTION
**Pull request by samsonasik**
@jails based on travis update to remove php 5.4 https://github.com/kahlan/kahlan/commit/f6ea0f3c653f76fb8b1daec47d6f7439af8179ef

### CODE REVIEW

**Comment by jails** [comment]
:+1:

**Comment by samsonasik** [comment]
how about in doc ? should we create 4.0 branch in https://github.com/kahlan/docs ?

**Comment by jails** [comment]
I already updated the doc repo so you can browse both 3.x & 4.x versions (https://github.com/kahlan/docs/commit/d321e19cbf9b73228efd1be5790d46eba267ebb9)
I will deploy it on github pages once the 4.0 will be tagged and once the filter API documentation part will be updated.
Meanwhile you can run `cousous preview` to see what the documentation looks like locally.

**Comment by samsonasik** [comment]
thank you 👍

**Pull request merged**
