### PR TITLE
Update documentation for Kahlan 3.0

### PR DESCRIPTION
**Pull request by jasonmccreary**
This PR contains commits for updating the documentation for Kahlan 3.0 as well as providing consistent language, tone, and code samples.

This is a *Work in Progress* - **do not merge**.

### CODE REVIEW

**Comment by jasonmccreary** [comment]
This is just a first pass. It contains:

- Initial proofreading with a focus on spelling and grammar mistakes.
- Consistent style and format of the code samples
- Removing or condensing sections

Next, I plan to rewrite the *DSL*, *Expectations*, *Matcher*, and *Stubs* section to include updates for 3.0, but also read more like a book.

The goal is for the documentation to be written in a format where it can be read from start to finish. Laravel has done this with its documentation and I believe it has been very successful.

**Comment by jails** [comment]
Awesome PR :+1: !
My only concern is related to https://github.com/crysalead/kahlan/pull/161/commits/cf7e4b321a12fc57db1035e54fe7b87a7dd0b80d. I totally embraced [http://betterspecs.org/ conventions](http://betterspecs.org/#should) which is imo the best resource to use for promoting spec-based testing.

**Comment by jasonmccreary** [comment]
Completely agree with *Better Specs*. I didn't realize they were against this convention. In fact, I thought it was the convention. I've been writing my specs the *Bad* way for 2 years now!

I'll revert this when I continue the revisions. That's why I make small commits.

**Comment by jails** [comment]
Perfect !

**Comment by jasonmccreary** [comment]
Haven't forgotten about this. Going to rework a few more sections tomorrow. I assume I should still do the PRs here?

**Comment by jails** [comment]
Awesome !
Yeah just push your commits here, I'll handle the merge :+1:
Btw that's weird the tests doesn't pass, looks like you only changed doc files...

**Comment by jails** [comment]
Sorry for the mess, to be able to move Kahlan to its own repo I needed to rebase the dev branch. So imo the best option is to `cp` your `docs` directory somewhere and starting from a clean `dev` and copying `docs` files back.

**Comment by jails** [comment]
I cherry picked commits so I'm closing this.

**Comment by jails** [comment]
JFYI I extracted the documentation to its dedicated repo https://github.com/kahlan/docs

**Comment by jasonmccreary** [comment]
No worries. I'll reconnect the repo later today and add my recent updates. Hoping to get the second pass done by Monday. Then I'm going to write some Kahlan to *verify* the docs and do a final pass.

**Pull request closed without merging**
