### PR TITLE
Allow final class mocking

### LINKED ISSUE #327: Add a patcher to handle final classes
Hi !

Thanks for this super testing framework.

Currently I can't `Double::instance` on a class, after I instanciate it myself, in a previous specification (following the test suite order).

I tried to debug and fix it myself, but I don't have enough background.
I'm blocking here: https://github.com/kahlan/kahlan/blob/b0341a59cefd2697f6e104bbcf045ee36a189ea2/src/Plugin/Double.php#L97
IMO classes must be destroyed after each block to improve isolation.

I think an example worth than a long discussion.
I successfully reproduce the bug on a very simple repo.

Notice the subterfuge with `A` and `B` folders, because if specification order is reversed, the test suite is ✅.

https://github.com/Th3Mouk/debug-kahlan

You just have to clone and launch `make reproduce` command.

PS: I was wondering how I can contribute to improve documentation ?

Thanks for your time

### PR DESCRIPTION
**Pull request by Th3Mouk**
Resolve #327 

This implementation add the new patcher by default

### CODE REVIEW

**Comment by jails** [comment]
Good job :1st_place_medal:  ! I'm merging this as is but I'll take a look at it deeper this W.E.
Thank you !

**Comment by Th3Mouk** [comment]
I'm sorry I just found a mistake the spec should be 

```php
$double = Double::instance([
    'extends' => FinalClass::class,
]);
```

So the implementation is not working because during the `eval` in the `Double::classname` method, the content is 

```php
<?php
namespace Kahlan\Spec\Plugin\Double;

class Double0 extends \FinalClass {}
?>
```

And this class (\FinalClass) is not the right version I was expected the patched version (with final keyword removed). @jails how does it work ? I supposed all classes where processed and cached before execution.

TY

**Comment by Th3Mouk** [comment]
@jails After further investigation the FinalClass (fixture class) class seems to be autoloaded by composer. Like any others classes in a standard project. The patcher seems to be ok, because final classes are processed and cached correctly, and seems to be used correctly too. The problem is only on the `eval` instruction but I don't have the background of this instruction, I don't know if processed file are supposed to replace initial class in the autoloader.

**Comment by jails** [comment]
Yeah it's a bit tricking to test Kahlan with Kahlan itself. Once a class is loaded by composer it can't be patched anymore.
To make long story short, all kahlan patchers are not working when running kahlan specs. So to emulate some real kahlan patching behavior, it needs to be ran through a tricky boilerplate code.

**Pull request merged**
