### PR TITLE
Fixed parsing multiple PHP8 attributes in single line

### PR DESCRIPTION
**Pull request by michalfelski**

### CODE REVIEW

**Comment by samsonasik** [comment]
Could you fix unit test error on php <= 7.4? Thank you.

**Comment by michalfelski** [comment]
Fixed. I have added **skipIf** for other tests for attributes parsing. They don't make sense for PHP7 but worked before change in this pull request.

**Comment by samsonasik** [comment]
Looks good, @jails I am merging it and going to release 5.2.5

**Comment by samsonasik** [comment]
kahlan 5.2.5 released https://github.com/kahlan/kahlan/releases/tag/5.2.5 thank you @michalfelski

**Pull request merged**
