### PR TITLE
ReflectionType::__toString() is deprecated in php 7.4, replace with ReflectionType::getName()

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
travis failure is not related with this change, merging

**Comment by samsonasik** [comment]
I applied `method_exists($type, 'getName)` check in `dev`

**Comment by jails** [comment]
Seems it didn't fix completely the "`E_DEPRECATED` Function ReflectionType::__toString() is deprecated" error.
Looks like there's still some similar error in the travis logs https://travis-ci.org/kahlan/kahlan/jobs/575140429

**Comment by samsonasik** [comment]
should already fixed in latest dev branch for the ReflectionType::__toString

**Comment by jails** [comment]
I think the `getName()` should be applied whatever the type is built-in or not in 7.4.
This PR should fix it in all cases https://github.com/kahlan/kahlan/commit/9055d4ecd8a54443ab4317ca603408e1283c891b

**Comment by jails** [comment]
And I hope all these `E_DEPRECATED` Unbinding \$this of closure is deprecated` will be fixed once https://github.com/php/php-src/pull/4548 will be merged.

**Pull request merged**
