### PR TITLE
Fix PHP 8.3 get_class()

### PR DESCRIPTION
**Pull request by Shira-3749**

### CODE REVIEW

**Comment by samsonasik** [comment]
Could you try fix test error on php 7.3? Thank you.

**Comment by Shira-3749** [comment]
Hmm, this passes for me locally under PHP 7.3.33.

**Comment by samsonasik** [comment]
probably some github glitch, it seems working ok, thank you :+1:

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
I created new release for it https://github.com/kahlan/kahlan/releases/tag/5.2.6

**Pull request merged**
