### PR TITLE
Simplification of the symbols for Windows

### PR DESCRIPTION
**Pull request by fzed51**
Fix for #167

### CODE REVIEW

**Comment by samsonasik** [comment]
could you upload the screen shoot before and after changed ?

**Comment by fzed51** [comment]
the screen shoot
before
after

**Comment by samsonasik** [comment]
Thank you, please change target branch to `dev` and do rebase and fixes the conflict. I wrote blog post about doing rebase https://samsonasik.wordpress.com/2015/09/16/practical-git-4-rebasing-conflicted-task-branch-against-primary-branch/

**Comment by jails** [comment]
Isn't possible to [make powershell to support UTF-8 instead](https://gist.github.com/xoner/4671514) ?

**Comment by jails** [comment]
Ok I'm closing this and will handle it manually thanks for the head up.

**Comment by fzed51** [comment]
J'ai continué de travailler sur le sujet. Même si la console est paramétrée pour afficher de l'UTF-8, l'affichage n'est pas bon.
Il faut utiliser `"\xE2\x9C\x94"` pour `OK` et `"\xE2\x9C\x94"` pour `ERR`.

Google translate :
I continued to work on the subject. Even if the console is set to display UTF-8, the display is not good.
You must use `"\xE2\x9C\x94"` to `OK` and `"\xE2\x9C\x94"` to `ERR`.

**Pull request closed without merging**
